import '../models/product_model.dart';
import 'core/util/product_tag.dart';

class JumiaData {
  static final List<String> promoImages = [
    'https://ng.jumia.is/cms/0-6-anniversary/2025/Emoji-challenge/Desktop-Homepage-Slider_-712x384.gif',
    'https://ng.jumia.is/cms/0-6-anniversary/2025/Global-early-bird-deals/712X384_.jpg',
    'https://ng.jumia.is/cms/0-6-anniversary/2025/Flash-Sales/Desktop-Homepage-Slider_-712x384.gif',
    'https://ng.jumia.is/cms/0-1-weekly-cps/0-2025/Awoof-deals/May/AOTM_APRIL_MOTION_712x384.gif',
    'https://ng.jumia.is/cms/0-1-weekly-cps/0-2025/Week_22/Beauty_style/712X384.jpg',
    'https://ng.jumia.is/cms/0-1-weekly-cps/0-2025/Week_22/Children-s_Collection/712x384.gif',
  ];

  static final List<ProductModel> productItems = [
    ProductModel(
      id: '1',
      isOfficialStore: true,
      title: 'Stainless Steel Cookware Set',
      description: '10-piece non-stick cookware set for versatile cooking',
      price: 42900,
      imageUrls: [
        'https://images.unsplash.com/photo-1588279102567-67db026f11c0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fENPT0tXQVJFJTIwU0VUfGVufDB8fDB8fHww',
      ],
      rating: 4.5,
      totalUnits: 25,
      itemsLeft: 10,
      ratingCount: 120,
      ratingSum: 540,
      label: ProductTag.payOnDelivery(),
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '2',
      isOfficialStore: false,
      title: 'Ceramic Dinnerware Set',
      description: '16-piece dinnerware set with plates, bowls, and mugs',
      price: 15000,
      originalPrice: 25000,
      discountPercentage: 40,
      imageUrls: [
        'https://images.unsplash.com/photo-1599958681123-88cd5957db83?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2VyYW1pYyUyMGRpbm5lcndhcmV8ZW58MHx8MHx8fDA%3D',
      ],
      rating: 4.2,
      totalUnits: 30,
      itemsLeft: 10,
      ratingCount: 85,
      ratingSum: 357,
      label: ProductTag.nonReturnable(),
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '3',
      isOfficialStore: false,
      title: 'Electric Kettle',
      description: '1.7L stainless steel kettle with fast boil',
      price: 18500,
      originalPrice: 22000,
      discountPercentage: 16,
      imageUrls: [
        'https://media.istockphoto.com/id/1571815108/photo/close-up-shot-of-an-unrecognisable-woman-using-kettle-in-kitchen.jpg?s=1024x1024&w=is&k=20&c=Sx7l5iHqlUsDCNN4ix1p7acB73u4SR8Dz4E9nfq0rTU=',
      ],
      rating: 4.7,
      totalUnits: 35,
      itemsLeft: 9,
      ratingCount: 200,
      ratingSum: 940,
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '4',
      isOfficialStore: true,
      title: 'Blender with Glass Jar',
      description: 'High-power blender for smoothies and food prep',
      price: 35000,
      imageUrls: [
        'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8QkxFTkRFUnxlbnwwfHwwfHx8MA%3D%3D',
      ],
      rating: 4.3,
      totalUnits: 55,
      itemsLeft: 49,
      ratingCount: 150,
      ratingSum: 645,
      label: ProductTag.payOnDelivery(),
      brandId: 'Hilda\'s Kitchen',
    ),
  ];

  static final List<ProductModel> sponsoredProducts = [
    ProductModel(
      id: '1',
      isOfficialStore: true,
      title: 'Stainless Steel Cookware Set',
      description: '10-piece non-stick cookware set for versatile cooking',
      price: 42900,
      imageUrls: [
        'https://cdn.pixabay.com/photo/2017/02/15/10/39/salad-2068220_1280.jpg',
        'https://picsum.photos/300/300?random=1',
      ],
      rating: 4.5,
      totalUnits: 25,
      itemsLeft: 10,
      ratingCount: 120,
      ratingSum: 540,
      label: ProductTag.payOnDelivery(),
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '2',
      isOfficialStore: false,
      title: 'Ceramic Dinnerware Set',
      description: '16-piece dinnerware set with plates, bowls, and mugs',
      price: 15000,
      originalPrice: 25000,
      discountPercentage: 40,
      imageUrls: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzdyvmk7BrT2EuuPhzznwPmgThpoAxH700Og&s',
        'https://cdn.pixabay.com/photo/2016/03/05/19/02/hamburger-1238246_1280.jpg',
      ],
      rating: 4.2,
      totalUnits: 30,
      itemsLeft: 10,
      ratingCount: 85,
      ratingSum: 357,
      label: ProductTag.nonReturnable(),
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '3',
      isOfficialStore: false,
      title: 'Electric Kettle',
      description: '1.7L stainless steel kettle with fast boil',
      price: 18500,
      originalPrice: 22000,
      discountPercentage: 16,
      imageUrls: [
        'https://images.unsplash.com/photo-1571552879083-e93b6ea70d1d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8RUxFQ1RSSUMlMjBLRVRUTEV8ZW58MHx8MHx8fDA%3D',
        'https://images.unsplash.com/photo-1579752898926-3bcbc125ae2e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fEVMRUNUUklDJTIwS0VUVExFfGVufDB8fDB8fHww',
      ],
      rating: 4.7,
      totalUnits: 35,
      itemsLeft: 9,
      ratingCount: 200,
      ratingSum: 940,
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '4',
      isOfficialStore: true,
      title: 'Blender with Glass Jar',
      description: 'High-power blender for smoothies and food prep',
      price: 35000,
      imageUrls: [
        'https://plus.unsplash.com/premium_photo-1681826671576-8d612accc77a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YmxlbmRlcnxlbnwwfHwwfHx8MA%3D%3D',
        'https://cdn.pixabay.com/photo/2017/05/11/19/44/fresh-fruits-2305192_1280.jpg',
      ],
      rating: 4.3,
      totalUnits: 55,
      itemsLeft: 49,
      ratingCount: 150,
      ratingSum: 645,
      label: ProductTag.payOnDelivery(),
      brandId: 'Hilda\'s Kitchen',
    ),
  ];

  static final List<ProductModel> anniversaryDeals = [
    ProductModel(
      id: '4',
      isOfficialStore: true,
      title: 'Blender with Glass Jar',
      description: 'High-power blender for smoothies and food prep',
      price: 35000,
      imageUrls: [
        'https://plus.unsplash.com/premium_photo-1681826671576-8d612accc77a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YmxlbmRlcnxlbnwwfHwwfHx8MA%3D%3D',
        'https://cdn.pixabay.com/photo/2017/05/11/19/44/fresh-fruits-2305192_1280.jpg',
      ],
      rating: 4.3,
      totalUnits: 55,
      itemsLeft: 49,
      ratingCount: 150,
      ratingSum: 645,
      label: ProductTag.payOnDelivery(),
      brandId: 'Hilda\'s Kitchen',
    ),
    ProductModel(
      id: '4',
      isOfficialStore: false,
      title: 'Mechanical Keyboard RGB',
      description: 'Gaming keyboard with mechanical switches',
      price: 35000,
      imageUrls: ['https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop'],
      rating: 4.3,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '204',
      isOfficialStore: true,
      title: 'Philips Air Fryer HD9252/90',
      description: '4.1L Capacity, Rapid Air Technology, Digital Display',
      price: 120000,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/40/0629883/1.jpg?6147',
      ],
      rating: 4.6,
      itemsLeft: 5,
      brandId: 'Havit',
    ),

    ProductModel(
      id: '203',
      isOfficialStore: true,
      title: 'Infinix Smart 7',
      description: '6.6" HD+ Display, 4GB RAM, 64GB ROM, 5000mAh Battery',
      price: 85000,
      originalPrice: 95000,
      discountPercentage: 10,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/39/8857604/1.jpg?8011',
      ],
      rating: 4.3,
      itemsLeft: 15,
      brandId: 'Havit',
    ),
  ];

  static final List<ProductModel> electronics = [
    ProductModel(
      id: '1',
      isOfficialStore: false,
      title: 'Logitech H390 USB Headset',
      description: 'High-quality USB headset with noise-canceling microphone',
      price: 42900,
      imageUrls: ['https://images.unsplash.com/photo-1599669454699-248893623440?w=300&h=300&fit=crop'],
      rating: 4.5,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '2',
      isOfficialStore: false,
      title: 'Havit PC Gaming Cursor',
      description: 'Gaming headset with RGB lighting and surround sound',
      price: 15000,
      originalPrice: 25000,
      discountPercentage: 40,
      imageUrls: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=300&h=300&fit=crop'],
      rating: 4.2,
      itemsLeft: 25,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '3',
      isOfficialStore: false,
      title: 'Wireless Gaming Mouse',
      description: 'High precision wireless gaming mouse with RGB',
      price: 18500,
      originalPrice: 22000,
      discountPercentage: 16,
      imageUrls: ['https://images.unsplash.com/photo-1527814050087-3793815479db?w=300&h=300&fit=crop'],
      rating: 4.7,
      itemsLeft: 12,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '4',
      isOfficialStore: false,
      title: 'Mechanical Keyboard RGB',
      description: 'Gaming keyboard with mechanical switches',
      price: 35000,
      imageUrls: ['https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop'],
      rating: 4.3,
      brandId: 'Havit',
    ),
  ];

  static final List<ProductModel> xiaomiOfficialStoreItems = [
    ProductModel(
      id: '101',
      isOfficialStore: true,
      title: 'Xiaomi Redmi Note 13 Pro',
      description: '6.67" AMOLED, 8GB RAM, 256GB ROM, 5000mAh Battery',
      price: 189000,
      originalPrice: 210000,
      discountPercentage: 10,
      imageUrls: [
        'https://i01.appmifile.com/webfile/globalimg/in/cms/Redmi_Note_13_Pro_5G_Black.png',
      ],
      rating: 4.8,
      itemsLeft: 14,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '102',
      isOfficialStore: true,
      title: 'Xiaomi Smart Band 8',
      description: 'Fitness tracker with 1.62" AMOLED display, 16-day battery',
      price: 23000,
      imageUrls: [
        'https://i01.appmifile.com/webfile/globalimg/in/cms/Mi_Band_8_Black.png',
      ],
      rating: 4.6,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '103',
      isOfficialStore: true,
      title: 'Xiaomi Robot Vacuum Mop 2 Pro',
      description: 'High-efficiency cleaning with smart navigation and mopping',
      price: 179000,
      originalPrice: 200000,
      discountPercentage: 11,
      imageUrls: [
        'https://i01.appmifile.com/webfile/globalimg/in/cms/Robot_Vacuum_Mop_2_Pro_White.png',
      ],
      rating: 4.5,
      itemsLeft: 8,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '104',
      isOfficialStore: true,
      title: 'Xiaomi TV Box S 2nd Gen',
      description: '4K Ultra HD, Dolby Audio, Google TV',
      price: 45000,
      imageUrls: [
        'https://i01.appmifile.com/webfile/globalimg/in/cms/TV_Box_S_2nd_Gen_Black.png',
      ],
      rating: 4.4,
      itemsLeft: 20,
      brandId: 'Havit',
    ),
  ];

  static final List<ProductModel> phonesAndTablet = [
    ProductModel(
      id: '201',
      isOfficialStore: true,
      title: 'Samsung Galaxy A54 5G',
      description: '6.4" Super AMOLED, 8GB RAM, 128GB ROM, 5000mAh Battery',
      price: 295000,
      originalPrice: 320000,
      discountPercentage: 8,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/28/2223353/1.jpg?3444',
      ],
      rating: 4.7,
      itemsLeft: 10,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '202',
      isOfficialStore: true,
      title: 'Oraimo FreePods 3',
      description: 'True Wireless Earbuds with Noise Cancellation, 20-hour playtime',
      price: 25000,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/56/6975982/1.jpg?4201',
      ],
      rating: 4.5,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '203',
      isOfficialStore: true,
      title: 'Infinix Smart 7',
      description: '6.6" HD+ Display, 4GB RAM, 64GB ROM, 5000mAh Battery',
      price: 85000,
      originalPrice: 95000,
      discountPercentage: 10,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/39/8857604/1.jpg?8011',
      ],
      rating: 4.3,
      itemsLeft: 15,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '204',
      isOfficialStore: true,
      title: 'Philips Air Fryer HD9252/90',
      description: '4.1L Capacity, Rapid Air Technology, Digital Display',
      price: 120000,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/40/0629883/1.jpg?6147',
      ],
      rating: 4.6,
      itemsLeft: 5,
      brandId: 'Havit',
    ),
  ];

  static final List<ProductModel> niveaOfficialStoreItems = [
    ProductModel(
      id: '301',
      isOfficialStore: true,
      title: 'NIVEA Perfect & Radiant Body Lotion',
      description: '400ml, Even Tone, Vitamin C & E, SPF 15, 48h Moisturization',
      price: 3500,
      originalPrice: 4000,
      discountPercentage: 12,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/15/1713401/1.jpg?0547',
      ],
      rating: 4.6,
      itemsLeft: 25,
      brandId: 'Havit',
    ),
    ProductModel(
      id: '302',
      isOfficialStore: true,
      title: 'NIVEA MEN Fresh Active Roll-On Deodorant',
      description: '50ml, 48h Odor Protection, Fresh Scent',
      price: 1200,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/98/3213401/1.jpg?1011',
      ],
      rating: 4.5,
      brandId: 'Nivea',
    ),
    ProductModel(
      id: '303',
      isOfficialStore: true,
      title: 'NIVEA Luminous Even Glow Day Cream',
      description: '40ml, SPF 50, Thiamidol, Hydrates & Evens Skin Tone',
      price: 6500,
      originalPrice: 7200,
      discountPercentage: 10,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/55/1713401/1.jpg?5747',
      ],
      rating: 4.7,
      itemsLeft: 15,
      brandId: 'Nivea',
    ),
    ProductModel(
      id: '304',
      isOfficialStore: true,
      title: 'NIVEA Cocoa Nourish Body Lotion',
      description: '400ml, Cocoa Butter & Vitamin E, 48h Deep Moisturization',
      price: 3800,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/26/8523401/1.jpg?1668',
      ],
      rating: 4.4,
      itemsLeft: 20,
      brandId: 'Nivea',
    ),
  ];

  static final List<ProductModel> jumiaTopSellersItems = [
    ProductModel(
      id: '401',
      isOfficialStore: true,
      title: 'Infinix Hot 40 Pro',
      description: '6.78" AMOLED, 8GB RAM, 256GB ROM, 5000mAh Battery',
      price: 220000,
      originalPrice: 245000,
      discountPercentage: 10,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/78/456123/1.jpg',
      ],
      rating: 4.7,
      itemsLeft: 12,
      brandId: 'Transsion',
    ),
    ProductModel(
      id: '402',
      isOfficialStore: true,
      title: 'Oraimo FreePods 4',
      description: 'True Wireless Earbuds, ANC, 35-hour Playtime',
      price: 28000,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/90/789456/1.jpg',
      ],
      rating: 4.6,
      brandId: 'Transsion',
    ),
    ProductModel(
      id: '403',
      isOfficialStore: true,
      title: 'NIVEA Perfect & Radiant Body Lotion',
      description: '400ml, Even Tone, Vitamin C & E, SPF 15, 48h Moisturization',
      price: 3500,
      originalPrice: 4000,
      discountPercentage: 12,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/12/901234/1.jpg',
      ],
      rating: 4.6,
      itemsLeft: 25,
      brandId: 'Nivea',
    ),
    ProductModel(
      id: '404',
      isOfficialStore: true,
      title: 'Fashion Men’s Sneakers',
      description: 'Breathable Mesh, Lightweight, Casual White Sneakers',
      price: 15000,
      imageUrls: [
        'https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/23/567890/1.jpg',
      ],
      rating: 4.4,
      itemsLeft: 30,
      brandId: 'Paul',
    ),
  ];
}